140 integrate additional events into google analytics query into the prototype
pendulum-chain/vortex pull request #255
Opened 2024-11-05 17:24 UTC by ebma

It took me some time to figure out how to be able to properly watch the connected network. I noticed that the [watchChainId](https://wagmi.sh/core/api/actions/watchChainId) and [useChainId](https://wagmi.sh/react/api/hooks/useChainId) both don't fire when switching from or to a non-supported network, ie a network that is not defined in our `wagmiConfig`. Since only `polygon` is defined in our `wagmiConfig`, it never triggered when switching from any network to polygon.

Instead, we are now using the `chainId` contained in the data of the [useAccount](https://wagmi.sh/react/api/hooks/useAccount) hook as it's always updated when the network changes. 

## GA config
### New Variables
- `DLV | from_network` and `DLV | to_network`
- `DLV | account_address`

### New triggers
- `DL Event | network_change`

### Events
- New event `GA4 Event | network_change`
   - Has parameters `from_network` - > `{{DLV | from_network }}` and `to_network` -> `{{DLV | to_network}}` 
   - Has trigger `DL Event | network_change`
- Changed event `GA4 Event | wallet_connect`
   - Has new parameters `account_address` -> `{{DLV | account_address}}`   

Closes #140.

2024-11-05 18:30 UTC, TorstenStueber approved these changes
Looks very good!

2024-11-05 21:26 UTC, Sharqiewicz requested changes
Great changes! ✅ Just minor things

2024-11-05 21:26 UTC, Sharqiewicz commented on src/contexts/events.tsx
> +  }, [chainId, previousChainId]);
missing dependency: `trackEvent`

2024-11-05 21:26 UTC, Sharqiewicz commented on src/contexts/events.tsx
> +  }, [chainId, previousChainId]);
`previousChainId` is a useRef and it doesn't change across renders. We don't have to include it in the dependency array

2024-11-05 21:28 UTC, Sharqiewicz commented on src/contexts/events.tsx
> +      from_network: previousChainId.current || chainId,
We already check if `previousChainId.current` is undefined, we don't have to `|| chainId`

2024-11-08 10:05 UTC, ebma commented
Nice catch @Sharqiewicz, addressed all your comments ✔️

2024-11-08 21:24 UTC, gianfra-t approved these changes
Tested a few times normal cases and works okay 👍

2024-11-11 18:14 UTC, merged